### ISSUE TITLE
M2X Site going back in time

### ISSUE THREAD

**Issue by chenfli** [attm2x/m2x-service#12]
It appears one of our projects get a minus on last activity:

**Comment by fsaravia** [comment]
@chenfli I edited your post because you posted the API Keys of multiple devices, I suggest that you regenerate keys for your devices.

Yesterday, there was a DST change, it could be possible that it was the cause of the issue, if you happen to run into the same problem again, please post the following information in order to identify the problem

- Device id
- Time of last activity on the device (last update or last value pushed) - including timezone
- Time when you saw the error - including timezone

Thanks

**Comment by chenfli** [comment]
Hi @fsaravia ,
Here is the data:

 Device id - f87e5178f9c47220839b60b9e4d1a398
Time of last activity on the device (last update or last value pushed) - including timezone - 03/09/2015 15:05:48.754 UTC
Time when you saw the error - including timezone - 03/09/2015 15:05:48.754 UTC

**Comment by fsaravia** [comment]
@chenfli everything looks good on this side, did you see it happen again? If not I would think of a DST related issue

**Comment by fsaravia** [comment]
Closing this one as it became stale, @chenfli feel free to open a new issue if this is still happening to you :). Thanks!
