### ISSUE TITLE
M2X Site is not updating for V2 Succesfull api callls and m2x.att.com is less responsive

### ISSUE THREAD

**Issue by chenfli** [attm2x/m2x-service#2]
Hi,
I am using the m2x node.js (https://www.npmjs.com/package/m2x) node for passing CRUD Requests.
Alltohugh I get  a possitive answer, It is not reflected on the m2x.att.com site.
(My user name is cfliesher on m2x.att.com)

I think the site is less responsive depends on the time.
For example: I work on 10:30 IST (Jerusalem) which is about 02:20 CST (Texas Dallas), during this time the site is less responsive.
While working on 15:00 IST, it usually appears to be a more responsive site.

As for the problem of possitive responses but failed to see results on the M2X site, Here is an example.
For this request
Devices.prototype.postMultiple = function('1b2f98cc3b31b527c27ba14fe46c615c', 
{
  "humidity": [
    { "timestamp": "2015-01-01T19:15:00.981Z", "value": 32 },
    { "timestamp": "2015-01-01T20:15:00.124Z", "value": 30 },
    { "timestamp": "2015-01-29T21:15:00.124Z", "value": 15 }],
  "heat": [
    { "timestamp": "2014-01-23T19:15:00.874Z", "value": 88 },
    { "timestamp": "2014-01-26T20:15:00.752Z", "value": 60 },
    { "timestamp": "2014-01-29T21:15:00.752Z", "value": 75 } ]
    
  },
, callback)

I get 

Successful M2X Api call [202]
{ status: 'accepted' },

Thanks in advanced 
Chen

**Comment by Jbossalini** [comment]
@chenfli are you not seeing the updated values at all, or is it taking some time to show up in the GET or the GUI?

@trotttrotttrott has been doing some load testing over the last week, and there were some reboots of the database servers last night so that might be affecting performance.  I'll dig into the Librato metrics, which might reflect what you're seeing.

**Comment by chenfli** [comment]
Hi Joe,
The problem is that I don't see the updated values at all.

I don't think it has to do with the time zones, since now it's 10:27 CST and I still can't see the values (no graph neither view log). However, create stream does applicable on the m2x site.

Adding the values now (10:32 CST) retrieve 500  now.

I am trying to test the keys, charts and distributions. I know the latter is for PRO account. However, I am getting for both keys and charts.

 "payload": "You are not allowed to access this resource",
 "statusCode": 403

I am now verifying it against Restfull API to validate where this issue comes from.

If you have an update, drop me a line.

Thanks.

**Comment by Jbossalini** [comment]
The issue with the values not showing up in the GUI is because of the time range of the POSTed data.  Some of those values were for Jan 1, and the default view of the chart (and log list) is for only data with a *timestamp* from the last 6 hours. Try changing the default view to 60 days. @fsaravia  confirmed that the values are there in the database.

The keys and charts issue might be dependent on the type of API key you are using.  I'll have to look in depth on the node.js example, but try using your Master Key (Account Settings -> Master Key) for now and see if that solves the 403 problem.

**Comment by chenfli** [comment]
Thanks,

working with the Primary key works.

I'll close this issue after validate all keys/charts API.

**Comment by chenfli** [comment]
@Jbossalini , It seems that time stamp also works fine. I tried to send it future time stamp and got succes, not sure if it's an issue.

**Comment by chenfli** [comment]
The same goes for
// https://m2x.att.com/developer/documentation/v2/device#Delete-Device
Devices.prototype.deleteDevice = function(id, callback) {
  return this.del(helpers.url("/devices/%s", id), callback);
};

**Comment by fsaravia** [comment]
@chenfli that's not an issue :) we accept any kind of timestamp for the moment.
Can we close this?

**Comment by chenfli** [comment]
Works, plus m2x node js was fixed.
